# Generated by Django 6.0.5 on 2026-05-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_seller_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
