# Generated by Django 6.0.5 on 2026-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_no',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
