# Generated by Django 6.0.5 on 2026-05-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_available_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
