# Generated by Django 6.0.5 on 2026-05-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_product_available_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='/defaults/user-icon-1.png', upload_to='user-images/'),
        ),
    ]
