# Generated by Django 6.0.5 on 2026-05-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='defaults/user-icon-1.png', upload_to='product-images/'),
        ),
    ]
