# Generated by Django 6.0.5 on 2026-05-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_product_product_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('seller', 'name'), name='unique_seller_product'),
        ),
    ]
