# Generated by Django 6.0.5 on 2026-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_product_unique_seller_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fashion_type',
            field=models.CharField(choices=[('professional', 'professional'), ('old_money', 'old_money'), ('wedding', 'wedding')], default='professional', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='gender_type',
            field=models.CharField(choices=[('men', 'men'), ('women', 'women'), ('kids', 'kids')], default='men', max_length=100),
        ),
    ]
