# Generated by Django 6.0.5 on 2026-05-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_product_fashion_type_product_gender_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_name',
            field=models.CharField(default='Emerging-Company', max_length=100),
        ),
    ]
